### ISSUE TITLE
To-do list before Thursday, 2019-01-09

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/DSCI_532_Mental-health-survey-Tech#1]
- [ ] review Shiny app potentials

- [ ] Sabrina - first draft - section 1, 3

- [ ] Ting - second draft - section 2, 4

**Comment by sabrinatkk** [comment]
Sabrina's task - completed 

d539b1dff268ed1a3b31c66550d7b0ea0b74f807

**Comment by panntingg** [comment]
I've completed my part and updated the proposal.
